#!/command/with-contenv bash
exec s6-setuidgid unhealthy /usr/local/bin/prometheus \
  --config.file=/etc/prometheus/prometheus.yml \
  --storage.tsdb.path=/var/lib/prometheus \
  --storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-30d} \
  --web.listen-address=0.0.0.0:9090 \
  --web.enable-lifecycle \
  --web.enable-remote-write-receiver \
  --web.config.file=/run/prometheus/web-config.yml
